// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"time"
)

const getAuditRecord = `-- name: GetAuditRecord :one
SELECT event_id, event_type, aggregate_id, aggregate_version, producer, producer_impl, correlation_id, causation_id, actor_type, actor_id, actor_role, channel, occurred_at, metadata_valid, kafka_topic, kafka_partition, kafka_offset, payload, recorded_at FROM audit_records WHERE event_id = $1
`

func (q *Queries) GetAuditRecord(ctx context.Context, eventID string) (AuditRecord, error) {
	row := q.db.QueryRow(ctx, getAuditRecord, eventID)
	var i AuditRecord
	err := row.Scan(
		&i.EventID,
		&i.EventType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Producer,
		&i.ProducerImpl,
		&i.CorrelationID,
		&i.CausationID,
		&i.ActorType,
		&i.ActorID,
		&i.ActorRole,
		&i.Channel,
		&i.OccurredAt,
		&i.MetadataValid,
		&i.KafkaTopic,
		&i.KafkaPartition,
		&i.KafkaOffset,
		&i.Payload,
		&i.RecordedAt,
	)
	return i, err
}

const insertAuditRecords = `-- name: InsertAuditRecords :execrows
INSERT INTO audit_records (
    event_id, event_type, aggregate_id, aggregate_version, producer, producer_impl,
    correlation_id, causation_id, actor_type, actor_id, actor_role, channel,
    occurred_at, metadata_valid, kafka_topic, kafka_partition, kafka_offset, payload
)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::bigint[]),
    unnest($5::text[]),
    unnest($6::text[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::text[]),
    unnest($10::text[]),
    unnest($11::text[]),
    unnest($12::text[]),
    unnest($13::timestamptz[]),
    unnest($14::boolean[]),
    unnest($15::text[]),
    unnest($16::integer[]),
    unnest($17::bigint[]),
    unnest($18::bytea[])
ON CONFLICT (event_id) DO NOTHING
`

type InsertAuditRecordsParams struct {
	EventIds          []string    `json:"event_ids"`
	EventTypes        []string    `json:"event_types"`
	AggregateIds      []string    `json:"aggregate_ids"`
	AggregateVersions []int64     `json:"aggregate_versions"`
	Producers         []string    `json:"producers"`
	ProducerImpls     []string    `json:"producer_impls"`
	CorrelationIds    []string    `json:"correlation_ids"`
	CausationIds      []string    `json:"causation_ids"`
	ActorTypes        []string    `json:"actor_types"`
	ActorIds          []string    `json:"actor_ids"`
	ActorRoles        []string    `json:"actor_roles"`
	Channels          []string    `json:"channels"`
	OccurredAts       []time.Time `json:"occurred_ats"`
	MetadataValids    []bool      `json:"metadata_valids"`
	KafkaTopics       []string    `json:"kafka_topics"`
	KafkaPartitions   []int32     `json:"kafka_partitions"`
	KafkaOffsets      []int64     `json:"kafka_offsets"`
	Payloads          [][]byte    `json:"payloads"`
}

// Writes a batch in one statement. A record whose event_id is already stored
// (redelivery or a re-published event) is skipped; the row count says how many
// were new.
func (q *Queries) InsertAuditRecords(ctx context.Context, arg InsertAuditRecordsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuditRecords,
		arg.EventIds,
		arg.EventTypes,
		arg.AggregateIds,
		arg.AggregateVersions,
		arg.Producers,
		arg.ProducerImpls,
		arg.CorrelationIds,
		arg.CausationIds,
		arg.ActorTypes,
		arg.ActorIds,
		arg.ActorRoles,
		arg.Channels,
		arg.OccurredAts,
		arg.MetadataValids,
		arg.KafkaTopics,
		arg.KafkaPartitions,
		arg.KafkaOffsets,
		arg.Payloads,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
