// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: initial.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (id, name, description, owner_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, owner_id, status, created_at, updated_at
`

type CreateExampleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	OwnerID     string    `json:"owner_id"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRow(ctx, createExample,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Status,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExample = `-- name: GetExample :one
SELECT id, name, description, owner_id, status, created_at, updated_at FROM examples
WHERE id = $1
`

func (q *Queries) GetExample(ctx context.Context, id uuid.UUID) (Example, error) {
	row := q.db.QueryRow(ctx, getExample, id)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, description, owner_id, status, created_at, updated_at FROM examples
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListExamplesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error) {
	rows, err := q.db.Query(ctx, listExamples, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExampleStatus = `-- name: UpdateExampleStatus :one
UPDATE examples
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, description, owner_id, status, created_at, updated_at
`

type UpdateExampleStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateExampleStatus(ctx context.Context, arg UpdateExampleStatusParams) (Example, error) {
	row := q.db.QueryRow(ctx, updateExampleStatus, arg.ID, arg.Status)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
