// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error)
	GetExample(ctx context.Context, id uuid.UUID) (Example, error)
	ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error)
	UpdateExampleStatus(ctx context.Context, arg UpdateExampleStatusParams) (Example, error)
}

var _ Querier = (*Queries)(nil)
