// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetAuditRecord(ctx context.Context, eventID string) (AuditRecord, error)
	// Writes a batch in one statement. A record whose event_id is already stored
	// (redelivery or a re-published event) is skipped; the row count says how many
	// were new.
	InsertAuditRecords(ctx context.Context, arg InsertAuditRecordsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
