// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hunderaweke/dps-audit-service/internal/const/models"
	mock "github.com/stretchr/testify/mock"
)

// NewAudit creates a new instance of Audit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *Audit {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Audit{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Audit is an autogenerated mock type for the Audit type
type Audit struct {
	mock.Mock
}

type Audit_Expecter struct {
	mock *mock.Mock
}

func (_m *Audit) EXPECT() *Audit_Expecter {
	return &Audit_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Audit
func (_mock *Audit) Get(ctx context.Context, eventID string) (models.AuditRecord, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.AuditRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.AuditRecord, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.AuditRecord); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(models.AuditRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Audit_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Audit_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *Audit_Expecter) Get(ctx any, eventID any) *Audit_Get_Call {
	return &Audit_Get_Call{Call: _e.mock.On("Get", ctx, eventID)}
}

func (_c *Audit_Get_Call) Run(run func(ctx context.Context, eventID string)) *Audit_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Audit_Get_Call) Return(auditRecord models.AuditRecord, err error) *Audit_Get_Call {
	_c.Call.Return(auditRecord, err)
	return _c
}

func (_c *Audit_Get_Call) RunAndReturn(run func(ctx context.Context, eventID string) (models.AuditRecord, error)) *Audit_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type Audit
func (_mock *Audit) Record(ctx context.Context, recs []models.AuditRecord) (int64, error) {
	ret := _mock.Called(ctx, recs)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.AuditRecord) (int64, error)); ok {
		return returnFunc(ctx, recs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.AuditRecord) int64); ok {
		r0 = returnFunc(ctx, recs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.AuditRecord) error); ok {
		r1 = returnFunc(ctx, recs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Audit_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type Audit_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - recs []models.AuditRecord
func (_e *Audit_Expecter) Record(ctx any, recs any) *Audit_Record_Call {
	return &Audit_Record_Call{Call: _e.mock.On("Record", ctx, recs)}
}

func (_c *Audit_Record_Call) Run(run func(ctx context.Context, recs []models.AuditRecord)) *Audit_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.AuditRecord
		if args[1] != nil {
			arg1 = args[1].([]models.AuditRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Audit_Record_Call) Return(stored int64, err error) *Audit_Record_Call {
	_c.Call.Return(stored, err)
	return _c
}

func (_c *Audit_Record_Call) RunAndReturn(run func(ctx context.Context, recs []models.AuditRecord) (int64, error)) *Audit_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditLog creates a new instance of AuditLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLog {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AuditLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AuditLog is an autogenerated mock type for the AuditLog type
type AuditLog struct {
	mock.Mock
}

type AuditLog_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLog) EXPECT() *AuditLog_Expecter {
	return &AuditLog_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type AuditLog
func (_mock *AuditLog) Append(ctx context.Context, recs []models.AuditRecord) (int64, error) {
	ret := _mock.Called(ctx, recs)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.AuditRecord) (int64, error)); ok {
		return returnFunc(ctx, recs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.AuditRecord) int64); ok {
		r0 = returnFunc(ctx, recs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.AuditRecord) error); ok {
		r1 = returnFunc(ctx, recs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuditLog_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditLog_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - recs []models.AuditRecord
func (_e *AuditLog_Expecter) Append(ctx any, recs any) *AuditLog_Append_Call {
	return &AuditLog_Append_Call{Call: _e.mock.On("Append", ctx, recs)}
}

func (_c *AuditLog_Append_Call) Run(run func(ctx context.Context, recs []models.AuditRecord)) *AuditLog_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.AuditRecord
		if args[1] != nil {
			arg1 = args[1].([]models.AuditRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditLog_Append_Call) Return(n int64, err error) *AuditLog_Append_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *AuditLog_Append_Call) RunAndReturn(run func(ctx context.Context, recs []models.AuditRecord) (int64, error)) *AuditLog_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type AuditLog
func (_mock *AuditLog) Get(ctx context.Context, eventID string) (models.AuditRecord, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.AuditRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.AuditRecord, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.AuditRecord); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Get(0).(models.AuditRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuditLog_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AuditLog_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *AuditLog_Expecter) Get(ctx any, eventID any) *AuditLog_Get_Call {
	return &AuditLog_Get_Call{Call: _e.mock.On("Get", ctx, eventID)}
}

func (_c *AuditLog_Get_Call) Run(run func(ctx context.Context, eventID string)) *AuditLog_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditLog_Get_Call) Return(auditRecord models.AuditRecord, err error) *AuditLog_Get_Call {
	_c.Call.Return(auditRecord, err)
	return _c
}

func (_c *AuditLog_Get_Call) RunAndReturn(run func(ctx context.Context, eventID string) (models.AuditRecord, error)) *AuditLog_Get_Call {
	_c.Call.Return(run)
	return _c
}
