// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/hunderaweke/dps-audit-service/internal/const/models"
	mock "github.com/stretchr/testify/mock"
)

// NewExample creates a new instance of Example. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExample(t interface {
	mock.TestingT
	Cleanup(func())
}) *Example {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Example{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Example is an autogenerated mock type for the Example type
type Example struct {
	mock.Mock
}

type Example_Expecter struct {
	mock *mock.Mock
}

func (_m *Example) EXPECT() *Example_Expecter {
	return &Example_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Example
func (_mock *Example) Create(ctx context.Context, ex models.Example) (models.Example, error) {
	ret := _mock.Called(ctx, ex)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Example) (models.Example, error)); ok {
		return returnFunc(ctx, ex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Example) models.Example); ok {
		r0 = returnFunc(ctx, ex)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Example) error); ok {
		r1 = returnFunc(ctx, ex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Example_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Example_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ex models.Example
func (_e *Example_Expecter) Create(ctx any, ex any) *Example_Create_Call {
	return &Example_Create_Call{Call: _e.mock.On("Create", ctx, ex)}
}

func (_c *Example_Create_Call) Run(run func(ctx context.Context, ex models.Example)) *Example_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Example
		if args[1] != nil {
			arg1 = args[1].(models.Example)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_Create_Call) Return(example models.Example, err error) *Example_Create_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Example_Create_Call) RunAndReturn(run func(ctx context.Context, ex models.Example) (models.Example, error)) *Example_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Example
func (_mock *Example) Get(ctx context.Context, id uuid.UUID) (models.Example, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Example, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Example); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Example_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Example_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Example_Expecter) Get(ctx any, id any) *Example_Get_Call {
	return &Example_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Example_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Example_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_Get_Call) Return(example models.Example, err error) *Example_Get_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Example_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (models.Example, error)) *Example_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCreated provides a mock function for the type Example
func (_mock *Example) HandleCreated(ctx context.Context, ev models.ExampleCreatedEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for HandleCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ExampleCreatedEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Example_HandleCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreated'
type Example_HandleCreated_Call struct {
	*mock.Call
}

// HandleCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - ev models.ExampleCreatedEvent
func (_e *Example_Expecter) HandleCreated(ctx any, ev any) *Example_HandleCreated_Call {
	return &Example_HandleCreated_Call{Call: _e.mock.On("HandleCreated", ctx, ev)}
}

func (_c *Example_HandleCreated_Call) Run(run func(ctx context.Context, ev models.ExampleCreatedEvent)) *Example_HandleCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ExampleCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(models.ExampleCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_HandleCreated_Call) Return(err error) *Example_HandleCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Example_HandleCreated_Call) RunAndReturn(run func(ctx context.Context, ev models.ExampleCreatedEvent) error) *Example_HandleCreated_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Example
func (_mock *Example) List(ctx context.Context, page models.Page) ([]models.Example, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Page) ([]models.Example, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Page) []models.Example); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Page) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Example_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Example_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page models.Page
func (_e *Example_Expecter) List(ctx any, page any) *Example_List_Call {
	return &Example_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *Example_List_Call) Run(run func(ctx context.Context, page models.Page)) *Example_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Page
		if args[1] != nil {
			arg1 = args[1].(models.Page)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_List_Call) Return(examples []models.Example, err error) *Example_List_Call {
	_c.Call.Return(examples, err)
	return _c
}

func (_c *Example_List_Call) RunAndReturn(run func(ctx context.Context, page models.Page) ([]models.Example, error)) *Example_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function for the type Example
func (_mock *Example) MarkProcessed(ctx context.Context, id uuid.UUID) (models.Example, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Example, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Example); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Example_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type Example_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Example_Expecter) MarkProcessed(ctx any, id any) *Example_MarkProcessed_Call {
	return &Example_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, id)}
}

func (_c *Example_MarkProcessed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Example_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_MarkProcessed_Call) Return(example models.Example, err error) *Example_MarkProcessed_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *Example_MarkProcessed_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (models.Example, error)) *Example_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOwner provides a mock function for the type Example
func (_mock *Example) VerifyOwner(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOwner")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Example_VerifyOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOwner'
type Example_VerifyOwner_Call struct {
	*mock.Call
}

// VerifyOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Example_Expecter) VerifyOwner(ctx any, id any) *Example_VerifyOwner_Call {
	return &Example_VerifyOwner_Call{Call: _e.mock.On("VerifyOwner", ctx, id)}
}

func (_c *Example_VerifyOwner_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Example_VerifyOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Example_VerifyOwner_Call) Return(err error) *Example_VerifyOwner_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Example_VerifyOwner_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *Example_VerifyOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewExampleRepository creates a new instance of ExampleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExampleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExampleRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ExampleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ExampleRepository is an autogenerated mock type for the ExampleRepository type
type ExampleRepository struct {
	mock.Mock
}

type ExampleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExampleRepository) EXPECT() *ExampleRepository_Expecter {
	return &ExampleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ExampleRepository
func (_mock *ExampleRepository) Create(ctx context.Context, ex models.Example) (models.Example, error) {
	ret := _mock.Called(ctx, ex)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Example) (models.Example, error)); ok {
		return returnFunc(ctx, ex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Example) models.Example); ok {
		r0 = returnFunc(ctx, ex)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Example) error); ok {
		r1 = returnFunc(ctx, ex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExampleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExampleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ex models.Example
func (_e *ExampleRepository_Expecter) Create(ctx any, ex any) *ExampleRepository_Create_Call {
	return &ExampleRepository_Create_Call{Call: _e.mock.On("Create", ctx, ex)}
}

func (_c *ExampleRepository_Create_Call) Run(run func(ctx context.Context, ex models.Example)) *ExampleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Example
		if args[1] != nil {
			arg1 = args[1].(models.Example)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleRepository_Create_Call) Return(example models.Example, err error) *ExampleRepository_Create_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *ExampleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ex models.Example) (models.Example, error)) *ExampleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ExampleRepository
func (_mock *ExampleRepository) Get(ctx context.Context, id uuid.UUID) (models.Example, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Example, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Example); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExampleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ExampleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ExampleRepository_Expecter) Get(ctx any, id any) *ExampleRepository_Get_Call {
	return &ExampleRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *ExampleRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ExampleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleRepository_Get_Call) Return(example models.Example, err error) *ExampleRepository_Get_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *ExampleRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (models.Example, error)) *ExampleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ExampleRepository
func (_mock *ExampleRepository) List(ctx context.Context, page models.Page) ([]models.Example, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Page) ([]models.Example, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Page) []models.Example); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Page) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExampleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ExampleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page models.Page
func (_e *ExampleRepository_Expecter) List(ctx any, page any) *ExampleRepository_List_Call {
	return &ExampleRepository_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *ExampleRepository_List_Call) Run(run func(ctx context.Context, page models.Page)) *ExampleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Page
		if args[1] != nil {
			arg1 = args[1].(models.Page)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleRepository_List_Call) Return(examples []models.Example, err error) *ExampleRepository_List_Call {
	_c.Call.Return(examples, err)
	return _c
}

func (_c *ExampleRepository_List_Call) RunAndReturn(run func(ctx context.Context, page models.Page) ([]models.Example, error)) *ExampleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type ExampleRepository
func (_mock *ExampleRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.ExampleStatus) (models.Example, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 models.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ExampleStatus) (models.Example, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ExampleStatus) models.Example); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.ExampleStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExampleRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type ExampleRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status models.ExampleStatus
func (_e *ExampleRepository_Expecter) UpdateStatus(ctx any, id any, status any) *ExampleRepository_UpdateStatus_Call {
	return &ExampleRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *ExampleRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.ExampleStatus)) *ExampleRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.ExampleStatus
		if args[2] != nil {
			arg2 = args[2].(models.ExampleStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExampleRepository_UpdateStatus_Call) Return(example models.Example, err error) *ExampleRepository_UpdateStatus_Call {
	_c.Call.Return(example, err)
	return _c
}

func (_c *ExampleRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status models.ExampleStatus) (models.Example, error)) *ExampleRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewExampleCache creates a new instance of ExampleCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExampleCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExampleCache {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ExampleCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ExampleCache is an autogenerated mock type for the ExampleCache type
type ExampleCache struct {
	mock.Mock
}

type ExampleCache_Expecter struct {
	mock *mock.Mock
}

func (_m *ExampleCache) EXPECT() *ExampleCache_Expecter {
	return &ExampleCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type ExampleCache
func (_mock *ExampleCache) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExampleCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ExampleCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ExampleCache_Expecter) Delete(ctx any, id any) *ExampleCache_Delete_Call {
	return &ExampleCache_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ExampleCache_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ExampleCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleCache_Delete_Call) Return(err error) *ExampleCache_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExampleCache_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ExampleCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ExampleCache
func (_mock *ExampleCache) Get(ctx context.Context, id uuid.UUID) (models.Example, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Example
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Example, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Example); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Example)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ExampleCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ExampleCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ExampleCache_Expecter) Get(ctx any, id any) *ExampleCache_Get_Call {
	return &ExampleCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *ExampleCache_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ExampleCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleCache_Get_Call) Return(ex models.Example, found bool, err error) *ExampleCache_Get_Call {
	_c.Call.Return(ex, found, err)
	return _c
}

func (_c *ExampleCache_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (models.Example, bool, error)) *ExampleCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type ExampleCache
func (_mock *ExampleCache) Set(ctx context.Context, ex models.Example) error {
	ret := _mock.Called(ctx, ex)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Example) error); ok {
		r0 = returnFunc(ctx, ex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExampleCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type ExampleCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - ex models.Example
func (_e *ExampleCache_Expecter) Set(ctx any, ex any) *ExampleCache_Set_Call {
	return &ExampleCache_Set_Call{Call: _e.mock.On("Set", ctx, ex)}
}

func (_c *ExampleCache_Set_Call) Run(run func(ctx context.Context, ex models.Example)) *ExampleCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Example
		if args[1] != nil {
			arg1 = args[1].(models.Example)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExampleCache_Set_Call) Return(err error) *ExampleCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExampleCache_Set_Call) RunAndReturn(run func(ctx context.Context, ex models.Example) error) *ExampleCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

type EventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisher) EXPECT() *EventPublisher_Expecter {
	return &EventPublisher_Expecter{mock: &_m.Mock}
}

// PublishExampleCreated provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishExampleCreated(ctx context.Context, ev models.ExampleCreatedEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for PublishExampleCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ExampleCreatedEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishExampleCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishExampleCreated'
type EventPublisher_PublishExampleCreated_Call struct {
	*mock.Call
}

// PublishExampleCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - ev models.ExampleCreatedEvent
func (_e *EventPublisher_Expecter) PublishExampleCreated(ctx any, ev any) *EventPublisher_PublishExampleCreated_Call {
	return &EventPublisher_PublishExampleCreated_Call{Call: _e.mock.On("PublishExampleCreated", ctx, ev)}
}

func (_c *EventPublisher_PublishExampleCreated_Call) Run(run func(ctx context.Context, ev models.ExampleCreatedEvent)) *EventPublisher_PublishExampleCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ExampleCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(models.ExampleCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishExampleCreated_Call) Return(err error) *EventPublisher_PublishExampleCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishExampleCreated_Call) RunAndReturn(run func(ctx context.Context, ev models.ExampleCreatedEvent) error) *EventPublisher_PublishExampleCreated_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkflowStarter creates a new instance of WorkflowStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowStarter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WorkflowStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WorkflowStarter is an autogenerated mock type for the WorkflowStarter type
type WorkflowStarter struct {
	mock.Mock
}

type WorkflowStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowStarter) EXPECT() *WorkflowStarter_Expecter {
	return &WorkflowStarter_Expecter{mock: &_m.Mock}
}

// StartProcessExample provides a mock function for the type WorkflowStarter
func (_mock *WorkflowStarter) StartProcessExample(ctx context.Context, ev models.ExampleCreatedEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for StartProcessExample")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ExampleCreatedEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowStarter_StartProcessExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartProcessExample'
type WorkflowStarter_StartProcessExample_Call struct {
	*mock.Call
}

// StartProcessExample is a helper method to define mock.On call
//   - ctx context.Context
//   - ev models.ExampleCreatedEvent
func (_e *WorkflowStarter_Expecter) StartProcessExample(ctx any, ev any) *WorkflowStarter_StartProcessExample_Call {
	return &WorkflowStarter_StartProcessExample_Call{Call: _e.mock.On("StartProcessExample", ctx, ev)}
}

func (_c *WorkflowStarter_StartProcessExample_Call) Run(run func(ctx context.Context, ev models.ExampleCreatedEvent)) *WorkflowStarter_StartProcessExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ExampleCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(models.ExampleCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkflowStarter_StartProcessExample_Call) Return(err error) *WorkflowStarter_StartProcessExample_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowStarter_StartProcessExample_Call) RunAndReturn(run func(ctx context.Context, ev models.ExampleCreatedEvent) error) *WorkflowStarter_StartProcessExample_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountClient creates a new instance of AccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AccountClient is an autogenerated mock type for the AccountClient type
type AccountClient struct {
	mock.Mock
}

type AccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountClient) EXPECT() *AccountClient_Expecter {
	return &AccountClient_Expecter{mock: &_m.Mock}
}

// GetAccount provides a mock function for the type AccountClient
func (_mock *AccountClient) GetAccount(ctx context.Context, id string) (models.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 models.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountClient_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountClient_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AccountClient_Expecter) GetAccount(ctx any, id any) *AccountClient_GetAccount_Call {
	return &AccountClient_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *AccountClient_GetAccount_Call) Run(run func(ctx context.Context, id string)) *AccountClient_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountClient_GetAccount_Call) Return(account models.Account, err error) *AccountClient_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountClient_GetAccount_Call) RunAndReturn(run func(ctx context.Context, id string) (models.Account, error)) *AccountClient_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditStore creates a new instance of AuditStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AuditStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AuditStore is an autogenerated mock type for the AuditStore type
type AuditStore struct {
	mock.Mock
}

type AuditStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditStore) EXPECT() *AuditStore_Expecter {
	return &AuditStore_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type AuditStore
func (_mock *AuditStore) Record(ctx context.Context, entry models.AuditEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AuditEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditStore_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type AuditStore_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - entry models.AuditEntry
func (_e *AuditStore_Expecter) Record(ctx any, entry any) *AuditStore_Record_Call {
	return &AuditStore_Record_Call{Call: _e.mock.On("Record", ctx, entry)}
}

func (_c *AuditStore_Record_Call) Run(run func(ctx context.Context, entry models.AuditEntry)) *AuditStore_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AuditEntry
		if args[1] != nil {
			arg1 = args[1].(models.AuditEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditStore_Record_Call) Return(err error) *AuditStore_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditStore_Record_Call) RunAndReturn(run func(ctx context.Context, entry models.AuditEntry) error) *AuditStore_Record_Call {
	_c.Call.Return(run)
	return _c
}
